plugins:
  gitcoin_passport_enabled:
    client: true
    default: false
  gitcoin_passport_api_key:
    client: false
    secret: true
    default: ""
  gitcoin_passport_scorer_id:
    client: false
    default: ""
  gitcoin_passport_group_levels:
    client: false
    default: 0,5,10,20,40,80
  gitcoin_passport_auto_manage_groups:
    client: false
    default: true
  gitcoin_passport_ethereum_node_url:
    client: false
    default: "https://eth-mainnet.public.blastapi.io"
